demo_dbt:
  target: local
  outputs:
    cloud:
      type: postgres
      host: "{{ env_var('DBT_ASTRO_POSTGRES_HOST') }}"
      user: "{{ env_var('DBT_ASTRO_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_ASTRO_POSTGRES_PASSWORD') }}"
      port: "{{ env_var('DBT_ASTRO_POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('DBT_ASTRO_POSTGRES_DBNAME') }}"
      schema: "{{ env_var('DBT_ASTRO_POSTGRES_SCHEMA') }}"
      threads: 4
    local:
      type: postgres
      host: localhost
      user: alejlatorre
      password: password
      port: 5433
      dbname: dbt_dev
      schema: dbt
      threads: 4
